### PR TITLE
Try to fix RPi3 builds

### PR DESCRIPTION
**Pull request by Herrie82**
These haven't been touched in years, let's start with bringing in a lot of changes from meta-webos-raspberrypi. Basically most things except for the kernel & file system changes.

### CODE REVIEW

**Comment by Herrie82** [comment]
@shr-project This boots to UI, wifi works. WAM not behaving (crashing), but that's expected with some bits from OSE missing still. It's a good starting point to continue from at least.

**Comment by ericblade** [comment]
Confirm it's working, for the general case of "it gets to a UI, and the UI can do things".  It's crashing wam probably because of a profound lack of vram, which i'll be looking into shortly...

**Comment by Herrie82** [comment]
@shr-project Dropped the Seeed Voicecard patches :)

**Comment by Herrie82** [comment]
Closing this one seeing we're in Scarthgap now and it's booting there too. https://github.com/webOS-ports/meta-rpi-luneos/pull/10

**Pull request closed without merging**
